[viewer]
    Title = "林可葸的测试博客"
    Description = "Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/473844125"
    Zhihu = "https://www.zhihu.com/people/ma-shen-zhi-lu"
    Avatar = "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Finews.gtimg.com%2Fnewsapp_bt%2F0%2F13147603927%2F1000.jpg&refer=http%3A%2F%2Finews.gtimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1647242040&t=c6108010ed46b4acebe18955acdd2d24"
    UserName = "林可葸"
    UserDesc = "testetst"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "U8al5uKYShWSwFv2-ynur_aKMqmM83H0jow7WtDo"
    QiniuSecretKey = "PmolSyM3LyFkPwT_X2rqH0kJhL1-0vyf6rTU-T9F"
    Valine = true
    ValineAppid = "i9VkMtiLO3RPCsJB0XouXzPQ-gzGzoHsz"
    ValineAppkey = "8qrsJ1wJs6cz8omVzyZ70MyJ"
    ValineServerURL = "https://i9vkmtil.lc-cn-n1-shared.com"